require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/**/*'
    - 'bin/*'
  NewCops: enable
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false